services:
  app:
    image: mrfzy00/spring-petclinic-docker:latest
    ports:
      - 8000:8000
      - 8080:80
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://postgresdb/petclinic
    volumes:
      - ./:/app
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: