services:
  app:
    image: mrfzy00/spring-petclinic-docker:latest
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: